import * as pdfjsLib from "pdfjs-dist"
import type { TextItem } from "pdfjs-dist/types/src/display/api"
// Vite resolves this to a hashed URL for the pdf.js worker bundle.
import workerUrl from "pdfjs-dist/build/pdf.worker.min.mjs?url"
import jEpub from "jepub"
import JSZip from "jszip"

pdfjsLib.GlobalWorkerOptions.workerSrc = workerUrl

export interface EpubMetadata {
  title: string
  author: string
  publisher?: string
  description?: string
}

// Characters illegal in XML 1.0: control chars below 0x20 except tab/newline/CR,
// plus the U+FFFE/U+FFFF non-characters. PDF text extraction occasionally emits
// these, which would otherwise make the chapter XHTML not well-formed.
// eslint-disable-next-line no-control-regex
const INVALID_XML_CHARS = /[\x00-\x08\x0B\x0C\x0E-\x1F\uFFFE\uFFFF]/g

function sanitize(text: string): string {
  return text.replace(INVALID_XML_CHARS, "")
}

function escapeHtml(text: string): string {
  return sanitize(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
}

/**
 * Renumber every NCX `playOrder` sequentially (1, 2, 3, …). jepub can emit
 * duplicate values, which EPUB 2 forbids unless they point to the same target
 * (epubcheck RSC-005). Sequential unique values are always valid.
 */
function fixNcxPlayOrder(xml: string): string {
  let n = 0
  return xml.replace(/playOrder="\d+"/g, () => `playOrder="${++n}"`)
}

/**
 * Rebuild an EPUB zip so the `mimetype` entry is first and STORED (uncompressed),
 * as required by the OCF spec, and fix the NCX play order. jepub/JSZip otherwise
 * trip epubcheck (PKG-007 / RSC-005) and stricter readers like Send-to-Kindle.
 */
async function normalizeOcf(epubBlob: Blob): Promise<Blob> {
  const src = await JSZip.loadAsync(epubBlob)
  const out = new JSZip()

  // mimetype must be the very first entry and uncompressed.
  out.file("mimetype", "application/epub+zip", { compression: "STORE" })

  for (const entry of Object.values(src.files)) {
    if (entry.dir || entry.name === "mimetype") continue
    if (entry.name.toLowerCase().endsWith(".ncx")) {
      const xml = await entry.async("string")
      out.file(entry.name, fixNcxPlayOrder(xml), { compression: "DEFLATE" })
    } else {
      const data = await entry.async("uint8array")
      out.file(entry.name, data, { compression: "DEFLATE" })
    }
  }

  return out.generateAsync({
    type: "blob",
    mimeType: "application/epub+zip",
  })
}

/**
 * Convert a (merged) PDF into an EPUB.
 *
 * First-pass, text-based conversion: extracts the text layer of each page with
 * pdf.js and lays it out as one EPUB chapter per page. Scanned PDFs without a
 * text layer produce empty pages (OCR would be needed).
 *
 * @param pdfBytes Raw PDF bytes (e.g. the output of mergePdfs).
 * @param meta     EPUB metadata (title, author, ...).
 * @returns The generated EPUB as a spec-compliant Blob, ready to download.
 */
export async function pdfToEpub(
  pdfBytes: Uint8Array,
  meta: EpubMetadata,
): Promise<Blob> {
  const pdf = await pdfjsLib.getDocument({ data: pdfBytes }).promise

  const epub = new jEpub()
  epub.init({
    i18n: "en",
    title: meta.title,
    author: meta.author,
    publisher: meta.publisher || "pdf-to-epub",
    description: meta.description || "",
  })

  for (let pageNum = 1; pageNum <= pdf.numPages; pageNum++) {
    const page = await pdf.getPage(pageNum)
    const content = await page.getTextContent()

    const text = content.items
      .map((item) => ("str" in item ? (item as TextItem).str : ""))
      .join(" ")
      .replace(/\s+/g, " ")
      .trim()

    const html = text
      ? `<p>${escapeHtml(text)}</p>`
      : "<p><em>(no extractable text on this page)</em></p>"

    epub.add(`Page ${pageNum}`, html)
  }

  // jepub references a notes page in its manifest; create it so the EPUB
  // doesn't point at a missing file (epubcheck RSC-001).
  epub.notes(`Generated by pdf-to-epub from ${pdf.numPages} page(s).`)

  const raw = (await epub.generate("blob")) as Blob
  return normalizeOcf(raw)
}
